// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package apm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type httpredDsCtx struct {
	_     structs.HostLayout
	Ts    uint64
	Dport uint16
	_     [6]byte
}

type httpredHttpEvent struct {
	_      structs.HostLayout
	DurNs  uint64
	Port   uint16
	Status uint16
	Kind   uint8
	Pad0   uint8
	Pad1   uint16
}

type httpredRecvCtx struct {
	_   structs.HostLayout
	Sk  uint64
	Buf uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	httpredMapDownstreamPorts = "downstream_ports"
	httpredMapDsPending       = "ds_pending"
	httpredMapDsStart         = "ds_start"
	httpredMapEvents          = "events"
	httpredMapInflight        = "inflight"
	httpredMapRecvs           = "recvs"
	httpredMapWatchedPorts    = "watched_ports"
	httpredProgTcpRecvEnter   = "tcpRecvEnter"
	httpredProgTcpRecvExit    = "tcpRecvExit"
	httpredProgTcpSendEnter   = "tcpSendEnter"
	httpredVarUnusedHttpEvent = "unused_http_event"
)

// loadHttpred returns the embedded CollectionSpec for httpred.
func loadHttpred() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HttpredBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load httpred: %w", err)
	}

	return spec, err
}

// loadHttpredObjects loads httpred and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*httpredObjects
//	*httpredPrograms
//	*httpredMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHttpredObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadHttpred()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// httpredSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpredSpecs struct {
	httpredProgramSpecs
	httpredMapSpecs
	httpredVariableSpecs
}

// httpredProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpredProgramSpecs struct {
	TcpRecvEnter *ebpf.ProgramSpec `ebpf:"tcpRecvEnter"`
	TcpRecvExit  *ebpf.ProgramSpec `ebpf:"tcpRecvExit"`
	TcpSendEnter *ebpf.ProgramSpec `ebpf:"tcpSendEnter"`
}

// httpredMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpredMapSpecs struct {
	DownstreamPorts *ebpf.MapSpec `ebpf:"downstream_ports"`
	DsPending       *ebpf.MapSpec `ebpf:"ds_pending"`
	DsStart         *ebpf.MapSpec `ebpf:"ds_start"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	Inflight        *ebpf.MapSpec `ebpf:"inflight"`
	Recvs           *ebpf.MapSpec `ebpf:"recvs"`
	WatchedPorts    *ebpf.MapSpec `ebpf:"watched_ports"`
}

// httpredVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpredVariableSpecs struct {
	UnusedHttpEvent *ebpf.VariableSpec `ebpf:"unused_http_event"`
}

// httpredObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHttpredObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpredObjects struct {
	httpredPrograms
	httpredMaps
	httpredVariables
}

func (o *httpredObjects) Close() error {
	return _HttpredClose(
		&o.httpredPrograms,
		&o.httpredMaps,
	)
}

// httpredMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHttpredObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpredMaps struct {
	DownstreamPorts *ebpf.Map `ebpf:"downstream_ports"`
	DsPending       *ebpf.Map `ebpf:"ds_pending"`
	DsStart         *ebpf.Map `ebpf:"ds_start"`
	Events          *ebpf.Map `ebpf:"events"`
	Inflight        *ebpf.Map `ebpf:"inflight"`
	Recvs           *ebpf.Map `ebpf:"recvs"`
	WatchedPorts    *ebpf.Map `ebpf:"watched_ports"`
}

func (m *httpredMaps) Close() error {
	return _HttpredClose(
		m.DownstreamPorts,
		m.DsPending,
		m.DsStart,
		m.Events,
		m.Inflight,
		m.Recvs,
		m.WatchedPorts,
	)
}

// httpredVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHttpredObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpredVariables struct {
	UnusedHttpEvent *ebpf.Variable `ebpf:"unused_http_event"`
}

// httpredPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHttpredObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpredPrograms struct {
	TcpRecvEnter *ebpf.Program `ebpf:"tcpRecvEnter"`
	TcpRecvExit  *ebpf.Program `ebpf:"tcpRecvExit"`
	TcpSendEnter *ebpf.Program `ebpf:"tcpSendEnter"`
}

func (p *httpredPrograms) Close() error {
	return _HttpredClose(
		p.TcpRecvEnter,
		p.TcpRecvExit,
		p.TcpSendEnter,
	)
}

func _HttpredClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed httpred_arm64_bpfel.o
var _HttpredBytes []byte
