#!/bin/sh
### BEGIN INIT INFO
# Provides:          wakora-agent
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Wakora Agent
### END INIT INFO

DAEMON=/usr/local/bin/wakora
PIDFILE=/run/wakora-agent.pid

case "$1" in
  start)
    start-stop-daemon --start --quiet --background --make-pidfile \
      --pidfile $PIDFILE --exec $DAEMON -- $WAKORA_ARGS
    ;;
  stop)
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    rm -f $PIDFILE
    ;;
  restart)
    "$0" stop
    sleep 1
    "$0" start
    ;;
  status)
    if start-stop-daemon --status --pidfile $PIDFILE; then
      echo "wakora-agent running"
    else
      echo "wakora-agent stopped"
      exit 3
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 2
    ;;
esac
